baseURL: 'https://pavancv.github.io/chintana/'
languageCode : 'en-us'
title : 'चिन्तन'

markup:
  goldmark:
      renderer:
        unsafe: true

relativeURLs : true

Params:
  booklist: data/books.yaml